Hola, Carlos

Como podrás apreciar en el repositorio que he creado para esta actividad, el último paso que he podido alcanzar ha sido el de la creación de detail.html; aunque,
realmente, la principal complicación para que no pudiera realizar la actividad al completo reside en que no he podido obtener una visualización en localhost de los 
datos del csv en index.html. A pesar de que la ejecución de "Python app.py" se producía correctamente y no se indicaban errores, localhost se mostraba de la manera 
que puede apreciarse en la imagen que te adjunto. He tratado de explotar todas las soluciones que nos has proporcionado: ya sea eliminando “.decode('UTF-8')", googleando
la incidencia e incluso recurriendo a Stackflow, donde he consultado la siguiente bibliografía, sin éxito:

https://stackoverflow.com/questions/12468179/unicodedecodeerror-utf8-codec-cant-decode-byte-0x9c
https://stackoverflow.com/questions/5552555/unicodedecodeerror-invalid-continuation-byte

Desgraciadamente, al no poder gozar de ningún tipo de soporte de ayuda dadas las fechas, me he visto obligado a desistir de la tarea dado que, de otro modo, no podré
afrontar el resto de casos que constan en la asignatura.
